### ISSUE TITLE
Uri's view rejections

### ISSUE THREAD

**Issue by gilgardosh** [Urigo/accounter-fullstack#120]
Issues:
- [x] selection requires touch (add null option, make default) #124 
- [x] insert ledger failing #123 
- [x] Charge tag suggestions not working on new design #125 
- [x] vat is updating (from null to null), should be removed before mutation sent #126 
- [ ] cannot generate creditcard ledger automatically
- [x] add vat back, add amount to charge, use all_transactions currency for amount, vat, withholdingTax (edited only on amount) #128 

- [x] temporary add account number & type to charge #121 
- [x] No label for tags #125 
- [x] insert/generate buttons are not available if no data #127 
- [x] show insert ledger as card under the charge (so you can see charge details) #130 
- [x] UI that shows charge data aside for update/insert forms #130 
- [x] add credit/debit counterparties to documents table (and to UI insert/update) #131
- [x] unlink document from charge #129 
- [x] link documents to charge flow+UI (can use test-server logic) #133 

- [x] update email listener (on test-server) to use documents table
- [x] add trigger to update (and link) documents on insert to email_invoices
- [x] deb7012a-fcc5-4dff-9080-cb088996bdf2 move to crisp charge
- [ ] slooooooowwww. paginate

- [x] local currency should default to ILS #142
- [x] insert ledger still not working #141
