### ISSUE TITLE
Documents matcher rejections 

### ISSUE THREAD

**Issue by gilgardosh** [Urigo/accounter-fullstack#140]
Tasks:
- [x] create reversed matcher: on all-charges add match-document function that shows top 3 picks and full list ordered by date #149 
- [x] delete document button #161 
- [x] show document extended info inputs according to type selection #143 
- [x] merge documents table and matcher

misc
- [x] on Israeli transactions, debit date is missing. If no value => (If creditcard + ILS use event_date). solve it on DB/PubSub later #153
